export const styles = {
  pageBackground: { backgroundColor: '#0f172a', minHeight: '100vh', color: '#f8fafc', fontFamily: 'Inter, system-ui, sans-serif' },
  container: { maxWidth: '1140px', margin: '0 auto', padding: '40px 20px' },
  loginContainer: { display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '100vh', backgroundColor: '#0f172a', fontFamily: 'Inter, system-ui, sans-serif' },
  loginCard: { backgroundColor: '#1e293b', padding: '48px', borderRadius: '16px', border: '1px solid #334155', textAlign: 'center', maxWidth: '400px', width: '100%' },
  logoBadge: { 
    width: '40px', 
    height: '40px', 
    display: 'inline-flex', 
    alignItems: 'center', 
    justifyContent: 'center', 
    borderRadius: '10px', 
    backgroundColor: '#6366f1', 
    padding: '4px', 
    overflow: 'hidden', 
  },
  logoImage: {
    width: '100%',
    height: '100%',
    objectFit: 'contain', 
    display: 'block',
  },
  githubBtn: { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: '10px', backgroundColor: '#24292f', color: '#fff', padding: '12px 20px', borderRadius: '8px', textDecoration: 'none', fontWeight: '600', width: '100%', border: '1px solid #475569' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '32px', borderBottom: '1px solid #334155', paddingBottom: '20px' },
  title: { fontSize: '22px', fontWeight: '700', margin: 0, color: '#f8fafc' },
  subtitle: { fontSize: '13px', color: '#94a3b8', margin: '2px 0 0 0' },
  userInfo: { display: 'flex', alignItems: 'center', gap: '10px' },
  avatar: { width: '32px', height: '32px', borderRadius: '50%', border: '1px solid #475569' },
  username: { fontSize: '14px', fontWeight: '500', color: '#cbd5e1' },
  logoutBtn: { backgroundColor: 'transparent', color: '#94a3b8', border: '1px solid #334155', padding: '6px 12px', borderRadius: '6px', cursor: 'pointer', fontSize: '13px' },
  actionSection: { display: 'flex', gap: '16px', flexWrap: 'wrap', alignItems: 'stretch', marginBottom: '32px' },
  filterToolbar: { display: 'flex', gap: '20px', flex: 1, flexWrap: 'wrap', alignItems: 'center', backgroundColor: '#1e293b', padding: '16px 20px', borderRadius: '12px', border: '1px solid #334155' },
  filterGroup: { display: 'flex', flexDirection: 'column', gap: '6px', flex: 1, minWidth: '180px' },
  label: { fontSize: '11px', fontWeight: '700', color: '#94a3b8', letterSpacing: '0.05em' },
  input: { padding: '8px 12px', border: '1px solid #334155', borderRadius: '6px', fontSize: '13px', backgroundColor: '#0f172a', color: '#f8fafc', outline: 'none' },
  rangeInput: { cursor: 'pointer', accentColor: '#6366f1' },
  select: { padding: '8px 12px', border: '1px solid #334155', borderRadius: '6px', fontSize: '13px', backgroundColor: '#0f172a', color: '#f8fafc', outline: 'none' },
  syncBtn: { backgroundColor: '#6366f1', color: '#fff', border: 'none', padding: '0 24px', borderRadius: '12px', fontWeight: '600', fontSize: '14px', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' },
  chartCard: { backgroundColor: '#1e293b', padding: '24px', borderRadius: '12px', marginBottom: '32px', border: '1px solid #334155' },
  grid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))', gap: '20px' },
  card: { backgroundColor: '#1e293b', border: '1px solid #334155', padding: '20px', borderRadius: '12px', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' },
  cardHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: '12px', marginBottom: '8px' },
  repoTitle: { margin: 0, fontSize: '16px', fontWeight: '600', color: '#f8fafc', wordBreak: 'break-word' },
  badge: { fontSize: '12px', fontWeight: '600', padding: '2px 8px', borderRadius: '12px', whitespace: 'nowrap' },
  repoDesc: { color: '#94a3b8', fontSize: '13px', marginBottom: '20px', lineHeight: '1.4', minHeight: '38px' },
  metricGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', borderTop: '1px solid #334155', paddingTop: '16px' },
  metricItem: { display: 'flex', flexDirection: 'column', gap: '2px' },
  metricLabel: { fontSize: '11px', color: '#64748b' },
  metricValue: { fontSize: '14px', fontWeight: '600', color: '#f8fafc' },
  stateCard: { backgroundColor: '#1e293b', border: '1px solid #334155', padding: '60px', borderRadius: '12px', textAlign: 'center' },
};